name: Run on Command

on:
  workflow_dispatch:

jobs:
  Update-Excell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step checks out your repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Set up Edge
        uses: microsoft/edge-devtools-action@v2
        with:
          # Specify the version of Edge to be installed
          version: 'latest'

      - name: Install required Python modules
        run: |
          pip install gspread oauth2client pandas openpyxl beautifulsoup4 msedge-selenium-tools selenium requests

      - name: Run Main Function
        run: python main.py
