name: Run Twice a Day

on:
  schedule:
    - cron: '34 23 * * *' # Runs at 23:03 (UTC)

jobs:
  Update-Excell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step checks out your repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install required Python modules
        run: |
          pip install gspread oauth2client pandas openpyxl beautifulsoup4 msedge-selenium-tools selenium requests

      - name: Run Main Function
        run: python main.py
