name: Twice Per Day

on:
  # At 07:00 and 12:00 every day, Pacific Time (PST/PDT)
    # Note: GitHub Actions uses UTC time
    # PST (Winter): UTC - 8 hours
    # PDT (Summer): UTC - 7 hours
    # In December, PST is applicable, so UTC - 8 hours
    schedule:
      - cron: '0 20,23 * * *' # 07:00 and 12:00 PST (15:00 and 20:00 UTC)
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  Update-Excell:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step checks out your repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install required Python modules
        run: |
          pip install gspread oauth2client pandas openpyxl beautifulsoup4 lxml

      - name: Run Main Function in BackEnd directory
        run: |
          cd BackEnd
          python updateList.py
  Update-Database:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step checks out your repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install required Python modules
        run: |
          pip install gspread oauth2client pandas openpyxl beautifulsoup4 lxml sqlite3

      - name: Run Database
        run: |
          cd BackEnd
          python database.py
